INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_serie(score, count, title, image) VALUES (4.5, 2, 'Halo', 'https://www.themoviedb.org/t/p/original/nJUHX3XL1jMkk8honUZnUmudFb9.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (3.3, 3, 'Peaky Blinders: Sangue, Apostas e Navalhas', 'https://www.themoviedb.org/t/p/original/i0uajcHH9yogXMfDHpOXexIukG9.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'A Anatomia de Grey', 'https://www.themoviedb.org/t/p/original/9Hk49aTxoxtK2ynzdR2ILF6q2mn.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Cavaleiro da Lua', 'https://www.themoviedb.org/t/p/original/tkc7AVyUoG9VEeDvukN0TVqa24C.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'All of Us Are Dead', 'https://www.themoviedb.org/t/p/original/pTEFqAjLd5YTsMD6NSUxV6Dq7A6.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Os Simpsons', 'https://www.themoviedb.org/t/p/original/9n4dv0aGRb8Ma15H7jbWsY7Eg0N.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'WandaVision', 'https://www.themoviedb.org/t/p/original/eKrIIYLswMc2bFfF1pyY6esberq.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'The Good Doctor: O Bom Doutor', 'https://www.themoviedb.org/t/p/original/3o15JgAtHgluFkxH0F6ScdavBbn.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Euphoria', 'https://www.themoviedb.org/t/p/original/3Q0hd3heuWwDWpwcDkhQOA6TYWI.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Scorpion: Serviço de Inteligência', 'https://www.themoviedb.org/t/p/original/k1Edm68SE8JeOzyTafZnTOOuLTx.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Jujutsu Kaisen', 'https://www.themoviedb.org/t/p/original/g1rK2nRXSidcMwNliWDIroWWGTn.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Suits: Homens de Terno', 'https://www.themoviedb.org/t/p/original/ubEYUaE1EOBnSgb1OteAeGJP1E5.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Dr. House', 'https://www.themoviedb.org/t/p/original/gYXgFP5anlPn3bS5FNsNFZZTmng.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Loki', 'https://www.themoviedb.org/t/p/original/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Round 6', 'https://www.themoviedb.org/t/p/original/6gcHdboppvplmBWxvROc96NJnmm.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Komi Can't Communicate', 'https://www.themoviedb.org/t/p/original/p2Hyub0gWdNVnDRc5aC9oYMMXY.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Jovem Sheldon', 'https://www.themoviedb.org/t/p/original/uHa4RJ211SQZucg4EkcmOW8EnIU.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'NCIS: Investigação Naval', 'https://www.themoviedb.org/t/p/original/6b68fd3p0OpRXJZfZGLQ9Gs7kzl.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Big Bang: A Teoria', 'https://www.themoviedb.org/t/p/original/gXLGUSXp3ZLkjwX0x45NXCagiNH.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'One Piece', 'https://www.themoviedb.org/t/p/original/goKUd5y4lHU3qkW0XKKxmNSNcem.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Arcane', 'https://www.themoviedb.org/t/p/original/ohGz4HDYGTite1GmRhRuBMVAn03.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Ragnarok', 'https://www.themoviedb.org/t/p/original/1LRLLWGvs5sZdTzuMqLEahb88Pc.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Família Moderna', 'https://www.themoviedb.org/t/p/original/gGOZeGx3ggP5O9qvswRPN7PRVWn.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Inventando Anna', 'https://www.themoviedb.org/t/p/original/h8e5vYPuFTK9Dhv79CEiCVMq11c.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'The Mandalorian', 'https://www.themoviedb.org/t/p/original/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Dark', 'https://www.themoviedb.org/t/p/original/wSXJHO9WHLb0aCwvQrtco7vOmWA.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Doctor Who', 'https://www.themoviedb.org/t/p/original/ezk0jjMI24HoxRMSCzkc1IBRy0a.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'The Witcher', 'https://www.themoviedb.org/t/p/original/e5iqR3k7azXGK1tGaOLMnKycGku.jpg');
INSERT INTO tb_serie(score, count, title, image) VALUES (0, 0, 'Arquivo X', 'https://www.themoviedb.org/t/p/original/p0uhiJmkzlJsvTyn0KKiLwrwGwA.jpg');

INSERT INTO tb_score(serie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(serie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(serie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(serie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(serie_id, user_id, value) VALUES (2, 3, 4.0);